# Run Kaa IoT using PostgreSQL and MongoDB

# Note: you may ignore the Postgres error resembling: "ERROR:  constraint "...." of relation "...." does not exist"

version: '2'
services:
  jdbc:
    image: postgres:9.4
    networks:
      - back-tier
    volumes:
      - jdbc-data:/var/lib/postgresql/data/kaa-pgdata
    env_file: postgres-example.env
    environment:
      - PGDATA=/var/lib/postgresql/data/kaa-pgdata # Fixes FS volume issues
  zookeeper:
    image: jplock/zookeeper:3.4.8
    networks:
      - back-tier
    volumes:
      - zookeeper-data:/tmp/zookeeper
  mongo:
    image: mongo:3.2
    networks:
      - back-tier
    volumes:
      - mongo-data:/data/db
  kaa:
    image: cburr25/kaa:0.9.0
    # build: .
    env_file: ../kaa-example.env
    environment:
      - SQL_PROVIDER_NAME=postgresql
    depends_on:
      - jdbc
      - zookeeper
      - mongo
    networks:
      - back-tier
      - front-tier
    ports:
      - "8080:8080"
      - "9888:9888"
      - "9889:9889"
      - "9997:9997"
      - "9999:9999"
networks:
  back-tier:
    driver: bridge # overlay for Swarm (unreleased update)
  front-tier:
    driver: bridge # overlay for Swarm (unreleased update)
volumes:
  jdbc-data:
  mongo-data:
  zookeeper-data:
